.github/workflows/integration_test.yaml
tests/conftest.py
tests/integration/conftest.py
tests/integration/data/charm/charmcraft.yaml
tests/integration/helpers.py
tests/integration/requirements.txt
tests/integration/setup_private_endpoint.sh
tests/integration/test_charm.py
tests/integration/types.py

- Changes tests to use private endpoints
- Due to constraints of ARM64 nested virtualization, if we deploy ARM64 image builder charm on top of LXD VM (OpenStack runner VM -> LXD VM = 2 nested virt layers), the KVM is not available and the image bulid will fail.
None.
None.

chore: private endpoint juju access

---

tests/conftest.py
tests/integration/conftest.py
tests/integration/helpers.py
tests/integration/test_charm.py

Add support for dockerhub mirror for tests
Tests get timeout error due to rate limiting
N/A
N/A
None.

test: support dockerhub mirror for tests

---

charmcraft.yaml
src-docs/builder.py.md
src-docs/charm.py.md
src-docs/state.py.md
src/builder.py
src/charm.py
src/state.py
tests/integration/conftest.py
tests/integration/test_charm.py
tests/integration/types.py
tests/unit/factories.py
tests/unit/test_builder.py
tests/unit/test_charm.py
tests/unit/test_state.py

Applicable spec: ISD165
- Fixes rustc build for cryptography lib
- Introduces `experimental-external-build*` configuration options to enable external (OpenStack VM) building of images.
- Refactor running of builds to be using `juju-exec` which outputs the logs via `juju debug-logs` which allows easier log viewing and prep work for COS integration.
- This is in preparation for custom images buliding.
- `run` action added to be triggered by `juju-exec`. This pattern is also applied to GitHub runner operator.
- `charm.py` - Removed all callback functions and handles image uploading calls directly w/ juju-exec'ed run calls.
- `state.py` - Added state for external build configuration values.
- `builder.py` - Added flags for external build if enabled. Changed to use juju-exec calls for cron. …

feat: external builder

---

.github/workflows/integration_test.yaml
RELEASE-NOTES.md
src-docs/builder.py.md
src-docs/charm.py.md
src-docs/image.py.md
src-docs/state.py.md
src/builder.py
src/charm.py
src/image.py
src/state.py
tests/integration/conftest.py
tests/integration/data/charm/charmcraft.yaml
tests/integration/data/charm/src/charm.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/types.py
tests/unit/test_builder.py
tests/unit/test_charm.py
tests/unit/test_image.py
tests/unit/test_state.py

Applicable spec: N?A
- Runs the image builder in external OpenStack VM mode
- Switch to external VM build to enable bootstrapped juju (snaps: microk8s juju lxd).
- On image relation joined, Github runner will provide OpenStack credentials for it to upload the final image to.
- charm.py - now processes image builder joined event
- state.py - processes image builder relation data
- builder.py - adds flag to run external build

feat: external cloud

---

requirements.txt
src-docs/builder.py.md
src-docs/charm.py.md
src-docs/image.py.md
src-docs/state.py.md
src/builder.py
src/charm.py
src/image.py
src/state.py
tests/integration/conftest.py
tests/integration/helpers.py
tests/unit/conftest.py
tests/unit/factories.py
tests/unit/test_builder.py
tests/unit/test_charm.py
tests/unit/test_image.py
tests/unit/test_state.py

- Build an image per relation and uploads once per cloud.
- This is to allow prevention of uploading the same image multiple times per relation to the same cloud which would exhaust the number of revisions kept and invalidate the images shared over the relation data for older relations.
- on image relation joined - fetches the latest image for the cloud provided by the event's unit
- image.py - handle update relation to update the relation data for relation's cloud only.

feat: multiple cloud image uploads

---

src-docs/image.py.md
src/image.py
tests/unit/test_image.py

- Installs/updates clouds.yaml content on image relation joined, before trying to fetch image from given cloud.
- Fixes bug where image fetch fails due to the clouds.yaml not containing the clouds.yaml configuration for the unit that has just joined the relation.

fix: install clouds_yaml on relation joined

---

charmcraft.yaml
src-docs/state.py.md
src/state.py
tests/unit/test_state.py

- Adds support for building architecture using external builders.
- To support ARM64 deployments on AMD64 model using external builders.

feat: add support for different architecture

---

src-docs/charm.py.md
src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

- define the run event to trigger w/ CRON
- The juju-exec succeeds even with a non-existant event. This PR adds the event.
- Adds run event.

fix: define run event

---

src-docs/builder.py.md
src/builder.py

- Adds arch command for initialize process
- To support multiarch build
- None
- Addes arch cmd line option

fix: arch support init

---

charmcraft.yaml
src-docs/builder.py.md
src-docs/state.py.md
src/builder.py
src/state.py
tests/unit/factories.py
tests/unit/test_builder.py
tests/unit/test_charm.py
tests/unit/test_state.py

- Exposes configuration option to embed external script to be run at the end of user defined cloud-init script.
- Allows customisation of images via publicly available script.
- Added config option `script-url`.
- `state.py` now processes `script-url` configuration option.
- `builder.py` now parametrizes images with script-url option and passes the `script-url` flag to the cli.

feat: script url config

---

src/builder.py
tests/unit/test_builder.py

Fixes current cron retrigger build image which was not getting triggered due to missing EOF newline.
Fixes bug w/ CRON build.
None.
None.
None.

fix: cron newline

---

CODEOWNERS
CONTRIBUTING.md
tests/conftest.py
tests/integration/conftest.py
tox.ini

1. Use passwords from env vars in integration tests.
2. update codeowners
1. To avoid leaking secrets.
2. To get automatic reviews from the right people (according to the roadmap planning).

chore: use passwords from env vars in integration tests

---

app/src/github_runner_image_builder/config.py
app/src/github_runner_image_builder/templates/cloud-init.sh.j2
app/tests/unit/test_openstack_builder.py

The proxy for the image builder and the github-runner could be different. 
Even more, there could be two proxies in the github-runner, one for the manager and one for the runners.
We want to always install aproxy (and nft for focal), independently of the need for it in the image-builder. Otherwise we 
ould have to copy the same code in the github-runner, and we careful with the proxy when installing aproxy and nft.
Besides that, we are also installing socat, as it could be needed in the github-runner for proxying tmate.

Always install aproxy as it could be needed for the runner even if not needed in the builder

---

.github/workflows/integration_test.yaml
.github/workflows/integration_test_app.yaml
.github/workflows/promote_charm.yaml
RELEASE-NOTES.md
app/src/github_runner_image_builder/cli.py
app/src/github_runner_image_builder/cloud_image.py
app/src/github_runner_image_builder/config.py
app/src/github_runner_image_builder/openstack_builder.py
app/tests/conftest.py
app/tests/integration/conftest.py
app/tests/unit/test_cli.py
app/tests/unit/test_cloud_image.py
app/tests/unit/test_config.py
app/tests/unit/test_openstack_builder.py
charmcraft.yaml
src/state.py
tests/integration/conftest.py
tests/integration/test_charm.py
tests/unit/test_state.py

Applicable spec: [ISD-200](https://docs.google.com/document/d/1voLbTHbtUbLlVbOx8VgsBotqXBnMLzMi2nBmmbCQ9aY/edit?tab=t.0)
Add support for building an image on ppc64le architecture. Similar adaptions as done in https://github.com/canonical/github-runner-image-builder-operator/pull/83.
Teams would like to use runners on ppc64el.
n/a
Add `ppc64le` support to various places. Do support specifying `ppc64el` per config option, too, as this is the notation in the ubuntu/debian universe.
n/a
[ISD-200]: https://warthogs.atlassian.net/browse/ISD-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: ppc64le images

---

app/requirements.txt

The streaming image download is now supported and is released on OpenStack SDK v4.5.0 and we can start using that now :)
Keep following upstream rather than fork.
No user relevant changes

chore: reset openstackstdk to upstream

---

charmcraft.yaml

Fix the image builder doc link
The documentation is not displayed in https://charmhub.io/github-runner-image-builder

fix: image builder doc link in charmcraft.yaml

---

app/src/github_runner_image_builder/openstack_builder.py
docs/changelog.md
docs/explanation/charm-architecture.md
src/charm.py
tests/unit/test_charm.py

Only run image building on a relation changed event if there is cloud auth data present. Only upload the newly created image to this particular cloud.
We have observed long waiting periods for new GitHub Runner units for the image to be present. In particular, the image build ran despite having cloud authentication data. Additionally, uploading images to all other units took some time.
```
2025-04-09 11:45:31 INFO juju.worker.uniter.operation runhook.go:186 ran "image-relation-created" hook (via hook dispatching script: dispatch)
2025-04-09 13:48:44.771	
2025-04-09 11:48:44 INFO unit.image-builder-noble-amd64-ps6/0.juju-log server.go:325 image:385: Required relation data not yet set.
2025-04-09 13:48:44.771	
2025-04-09 11:48:44 WARNING …
```

fix: skip run if relation data is not ready

---

CODEOWNERS
docs/changelog.md
src/builder.py
src/charm.py
tests/integration/conftest.py
tests/integration/test_charm.py
tests/unit/test_builder.py
tests/unit/test_charm.py

Applicable spec: n/a
Don't run image build run on every relation changed, but instead reuse an already built image for that specific cloud.
We have a GitHub Runner deployment where most applications use the same cloud, which means an image is likely already present for a newly joined unit. Before this PR, every image relation changed triggered a new run, which is unnecessary, as images get rebuilt periodically anyway (default every 6 hours). We can speed up new deployments a lot by reusing the already existing image.
adaption to image relation changed as outlined above
Mostly the `builder.py` to fix `get_latest_images` (which was broken) and `charm.py` to use this function. 
n/a

Feat: reuse image id on relation changed

---

.gitignore
app/src/github_runner_image_builder/logging.py
app/tests/integration/conftest.py
app/tests/unit/test_cli.py
app/tests/unit/test_logging.py
src/charm.py
tests/integration/conftest.py
tests/integration/test_charm.py

- Adds timestamp to logging
- Changes log directory to /var/log/github-runner-image-builder/ for cos_agent to scrape
- Added testing artefacts to .gitignore
- Timestamp being invisible leads to harder debugging.
No user relevant changes.

feat: log timestamp

---

app/requirements.txt
app/src/github_runner_image_builder/cli.py
app/tests/unit/test_cli.py

- Fixes case sensitivity for click. This is blocking: https://github.com/canonical/github-runner-image-builder-operator/pull/117
- Blocking click updates / renovate updates.
No user facing changes (backwards compatible)

fix: click case insensitive

---

app/tests/integration/conftest.py
tests/integration/conftest.py
tox.ini

- Cleanup test images after a single module test
- The image is piling up on the test environment
No user relevant changes

test: cleanup test images
